#!/bin/sh
odin build vendor/wayland/scanner
./scanner /usr/share/wayland/wayland.xml vendor/wayland/wayland_protocol.odin
./scanner /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml vendor/wayland/xdg_shell_protocol.odin
